### ISSUE TITLE
Ghost and Colour difference

### ISSUE THREAD

**Issue by kingvision** [ppwwyyxx/panorama#10]
HI
    Thank you for your opened code.  I used your code for stitching image, and Imet the problem of ghost and color difference.
    How i should do ?
thanks

**Comment by ppwwyyxx** [comment]
Currently there is no mechanism in the code to handle ghost caused by moving object or different gain between images (if that's what you mean by color difference).
If the ghost is not on moving object, then it's a stitching quality problem and would need to be diagnosed case-by-case.

**Comment by zhangyunming** [comment]
yes,i have run the job on my windows vs2015,but it have ghost heavily! 
you can have a look at your result demo ,also have some ghost.
thanks

**Comment by ppwwyyxx** [comment]
When you're taking photos at close object (within several meters), try to make sure the camera lens doesn't move at all, as best as you can. 
Moving the camera lens would break the geometry assumption of the algorithm. But since you cannot perfectly fix it so ghost is inevitable. It's just for distant objects the ghost won't be as serious.
