### ISSUE TITLE
run into serious ghost diference

### ISSUE THREAD

**Issue by findeway** [ppwwyyxx/panorama#12]
Thanks for the open code. But I ran into some serious ghost problem. 
My running result always has ghost shadows. I tried some different test data captured from my android phone camera. They all do the same!
But your test data works fine.
Please tell me how can I fix it or optimize it?

**Comment by ppwwyyxx** [comment]
There could be different reasons. Lack of distinctive features, severe lens distortion, camera translation, object motion can all lead to ghost effect.
It is hard to tell what is the main issue in your case. To avoid camera translation could be the first thing to try. I can also take a look if you can send me some data.

**Comment by findeway** [comment]
Thanks for your reply, dude! 
Using a tripod gives me some stable images. And the result looks much better now.
I also found out that changing the NR_PARAM_PER_CAMERA value in the “incremental_bundle_adjuster.cc” can optimize the output. What does this param mean?

**Comment by ppwwyyxx** [comment]
It is the number of parameters to describe the pose of a camera. By geometry it should be 6.
Although I suppose setting it to a larger value won't have huge consequences because the extra parameters will be initialized with zeros and get optimized together with the 6 ones. But I'm certainly not expecting it to  become better. If you really see that changing this number is consistently helpful, this might be something I should investigate.
