### ISSUE TITLE
output as equirectangular

### ISSUE THREAD

**Issue by arpu** [ppwwyyxx/panorama#6]
Hello

is it possible to output the panorama as equirectangular for 360video on youtube ?

**Comment by ppwwyyxx** [comment]
Yes It's possible. Given input images with large vertical FOV it should work, in theory. However I don't have such test data.

**Comment by arpu** [comment]
i send you some samples to your email

**Comment by ppwwyyxx** [comment]
I run my code on your images. They didn't overlap enough so there is not enough keypoint match between them. I can only stitch the last four images.
![out](https://cloud.githubusercontent.com/assets/1381301/11706184/5e5f877a-9ec4-11e5-962b-26f63768e838.jpg)

There is still obvious mismatch (ghost), because your camera has large FOV thus large distortions. It's so obvious that the edge of fridge is not straight. My code doesn't handle lens distortions. They can be stitched better if the images can be preprocessed first using your camera parameters.

**Comment by arpu** [comment]
ok the input should be  preprocessed to Equirectangular
i use Fov 80 degree
 pto_gen --fov=80 -p 2 test22_r.jpeg
nona -o test22_r_equirectangular.jpg  test22_r.pto

sample
http://snag.gy/X9yRK.jpg  to this http://snag.gy/Pn16t.jpg

any idea how i can do this without hugin (pto_gen, nona)?

**Comment by ppwwyyxx** [comment]
After applying your command I still see obvious distortion, where lines are not straight.
For large fov lens, only having the fov won't be enough to un-distort the photo. A barrel distortion of three/four parameters are needed.

**Comment by arpu** [comment]
yes this is, what i want for 360video (Equirectangular)

**Comment by ppwwyyxx** [comment]
They will be distorted again in the result so lines won't be straight in the result. However as input they need to be un-distorted before processing (if the distortion is severe) so that the planar geometry will work.
Although I'm not sure after that it will produce better results, because simply apply the un-distortion and crop a largest rectangle will lose some part in the image, which will produce fewer overlaps.

**Comment by arpu** [comment]
i dont understand what you mean :/  the idea is to have a not straight result for 3060video (youtube)

**Comment by ppwwyyxx** [comment]
Straight lines in the input images don't necessarily turn into straight lines in the result.
In [this](https://raw.githubusercontent.com/ppwwyyxx/panorama/master/results/small/CMU0-all.jpg) example, the building in the middle is straight, originally.

But to infer any geometry from the images, straight lines in real world must be straight lines in the input image for now. It could be part of the program in the future but that might need a database of camera lens information, or some kind of guessing.

I use `mogrify -distort barrel "0.0 -0.0 -0.16009" input.jpg` to process your images. (The parameters are just a guess). And then the stitch is like this. No ghost any more.
![result](https://cloud.githubusercontent.com/assets/1381301/11944339/4cd84200-a813-11e5-9b71-deaf77d73ddc.jpg)

**Comment by fithisux** [comment]
So, the above discussion means that I can create  spherical panorama?

**Comment by ASchimek** [comment]
I'm also interested, to know wether it's possible to create spherical panos.

**Comment by ppwwyyxx** [comment]
Sorry I'm not sure what you mean by spherical panorama. At  least I couldn't find a definition for it on google.

**Comment by fithisux** [comment]
Spherical panorama == Equirectangular wrapped on the sphere with plate care
projection.

On Mon, Jan 18, 2016 at 6:01 PM, Yuxin Wu <notifications@github.com> wrote:

> Sorry I'm not sure what you mean by spherical panorama. At least I
> couldn't find a definition for it on google.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ppwwyyxx/panorama/issues/6#issuecomment-172570019>.
>



-- 
Dr. Vasileios Anagnostopoulos (MSc,PhD)
Researcher/Developer
ICCS/NTUA 9 Heroon Polytechneiou Str., Zografou 15773 Athens,Greece
T (+30) 2107723404 M (+30) 6936935388
E vanag@mail.ntua.gr<mailto:vanag@mail.ntua.gr> www.ntua.gr<
http://www.ntua.gr/>

**Comment by ppwwyyxx** [comment]
I don't know what you mean by 'wrapped on the sphere'. Could you give an example maybe?
Also, it seems to me that plate carree projection is exactly what I did in equirectangular projection. See [wiki](https://en.wikipedia.org/wiki/Equirectangular_projection) and [mathworld](http://mathworld.wolfram.com/EquirectangularProjection.html).

Anyway, as long as there is a formula, a new projection method is very easy to implement.

**Comment by fithisux** [comment]
In any case what is the way to stittch to equirectangular? Moreover, are masks supported? (input image + mask)

**Comment by ASchimek** [comment]
I think a spherical pano is a full 360 x 180 degree pano. Like the pano's used for example in google's street view.

**Comment by fithisux** [comment]
@ASchimek 
Exactly this.

But are masks supported? Can I send you https://github.com/ppwwyyxx my images to check?

**Comment by fithisux** [comment]
These are my 6 images + roi.

[cleared.zip](https://github.com/ppwwyyxx/panorama/files/97403/cleared.zip)

**Comment by ppwwyyxx** [comment]
Equirectangular is also 360x180. [wiki](http://www.wikiwand.com/en/Equirectangular_projection).
The program does produce equirectangular ouptut (or spherical, because I still didn't see the difference), given that input images have enough 360x180 FOV.
Although that could be a challenge for the algorithm, because sky is featureless and may not be easily stitched together. Apps like Google Camera can produce such output because they use sensor data from the phone.

Regarding your images @fithisux , even I myself couldn't figure out the direction of each image, let alone the algorithm. roi masks are not supported right now.

**Comment by fithisux** [comment]
Thank you very much for your time.

On Wed, Jan 20, 2016 at 5:23 PM, Yuxin Wu <notifications@github.com> wrote:

> Equirectangular is also 360x180. wiki
> <http://www.wikiwand.com/en/Equirectangular_projection>.
> The program does produce equirectangular ouptut (or spherical, because I
> still didn't see the difference), given that input images have enough
> 360x180 FOV.
> Although that could be a challenge for the algorithm, because sky is
> featureless and may not be easily stitched together. Apps like Google
> Camera can produce such output because they use sensor data from the phone.
>
> Regarding your images @fithisux <https://github.com/fithisux> , even I
> myself couldn't figure out the direction of each image, let alone the
> algorithm. roi masks are not supported right now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ppwwyyxx/panorama/issues/6#issuecomment-173236714>.
>



-- 
Dr. Vasileios Anagnostopoulos (MSc,PhD)
Researcher/Developer
ICCS/NTUA 9 Heroon Polytechneiou Str., Zografou 15773 Athens,Greece
T (+30) 2107723404 M (+30) 6936935388
E vanag@mail.ntua.gr<mailto:vanag@mail.ntua.gr> www.ntua.gr<
http://www.ntua.gr/>

**Comment by ppwwyyxx** [comment]
BTW, it looks like you have a lot of experience with creating panoramas. Is there any other good panorama softwares you're aware of? I could try them out and see what kind of features are expected.

**Comment by fithisux** [comment]
I just only use Hugin :-( and learning to do with OpenCV.

On Wed, Jan 20, 2016 at 6:34 PM, Yuxin Wu <notifications@github.com> wrote:

> BTW, it looks like you have a lot of experience with creating panoramas.
> Is there any other good panorama softwares you're aware of? I could try
> them out and see what kind of features are expected.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ppwwyyxx/panorama/issues/6#issuecomment-173263697>.
>



-- 
Dr. Vasileios Anagnostopoulos (MSc,PhD)
Researcher/Developer
ICCS/NTUA 9 Heroon Polytechneiou Str., Zografou 15773 Athens,Greece
T (+30) 2107723404 M (+30) 6936935388
E vanag@mail.ntua.gr<mailto:vanag@mail.ntua.gr> www.ntua.gr<
http://www.ntua.gr/>

**Comment by kumar-jitendra** [comment]
Hi
does this algorithm only work with horizontal/sideways  overlapping images(extreme right of first image and extreme left of second image) ?
because when i try to stitch with 2 images(first image's bottom and second image's top overlapping) . then result was completely distorted.
i have attached the images for your reference.

and also can we create 360x180 or equirectangular using this algo ?
 please reply asap. @ppwwyyxx 
![cb1](https://user-images.githubusercontent.com/69798884/101053877-4b5e8780-35ae-11eb-838b-a246e1d861c7.jpg)
![ct1](https://user-images.githubusercontent.com/69798884/101053902-51546880-35ae-11eb-8552-2999452239bc.jpg)
![out](https://user-images.githubusercontent.com/69798884/101053915-51ecff00-35ae-11eb-9ab5-3aa65b5afe69.jpg)
